services:
  app:
    image: ghcr.io/hoarder-app/hoarder:0.21.0
    environment:
      DATA_DIR: /data
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MEILI_ADDR: http://meilisearch:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      BROWSER_WEB_URL: http://chrome:9222
      MAX_ASSET_SIZE_MB: 20
      DISABLE_NEW_RELEASE_CHECK: "true"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - /mnt/applications/hoarder/data:/data
    networks:
      - default
      - traefik_default
    healthcheck:
      disable: true
    labels:
      traefik.enable: true
      traefik.http.routers.hoarder.entrypoints: websecure
      traefik.http.routers.hoarder.rule: Host(`${DOMAIN}`)
    restart: unless-stopped

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /mnt/applications/hoarder/meilisearch:/meili_data
    restart: unless-stopped

networks:
  traefik_default:
    external: true

x-dockge:
  urls:
    - https://${DOMAIN}
