apiVersion: v2
type: application
name: traefik
description: High Performance, Kubernetes Native Object Storage
annotations:
  title: MYMinIO
version: 1.0.0
appVersion: '2023-07-21'
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: jansauer
    url: https://www.truenas.com/
    email: dev@ixsystems.com
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
  - https://github.com/minio/minio
  - https://github.com/minio/charts
keywords:
  - jansauer
