apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: ClusterIP
  selector:
    app: {{ template "fullname" . }}
  ports:
    - name: websecure
      port: {{ .Values.traefikNetwork.websecurePort }}
      targetPort: websecure
    - name: web
      port: {{ .Values.traefikNetwork.webPort }}
      targetPort: targetPort
    - name: traefik
      port: 9000
      targetPort: 9001
