services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.9.5
    environment:
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
      WEBUI_URL: "https://openwebui.${DOMAIN}"
      ENABLE_OAUTH_PERSISTENT_CONFIG: false
      ENABLE_OAUTH_SIGNUP: true
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      OAUTH_UPDATE_PICTURE_ON_LOGIN: true
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
      OPENID_PROVIDER_URL: "${OIDC_ISSUER_URL}/.well-known/openid-configuration"
      OAUTH_PROVIDER_NAME: "PocketID"
      CORS_ALLOW_ORIGIN: "https://*.${DOMAIN}"
    volumes:
      - /mnt/applications/openwebui:/app/backend/data
    networks:
      - newt_default
    healthcheck:
      disable: true
    labels:
      - pangolin.proxy-resources.open-webui.name=open-webui
      - pangolin.proxy-resources.open-webui.full-domain=openwebui.${DOMAIN}
      - pangolin.proxy-resources.open-webui.protocol=http
      - pangolin.proxy-resources.open-webui.auth.sso-enabled=true
      - pangolin.proxy-resources.open-webui.targets[0].method=http
      - pangolin.proxy-resources.open-webui.targets[0].port=8080
    restart: unless-stopped

networks:
  default:
    external: true
    name: none
  newt_default:
    external: true
