version: "3.8"
services:
  overpass:
    image: wiktorn/overpass-api:0.7.62
    environment:
      OVERPASS_MODE: clone
      OVERPASS_CLONE_SOURCE: http://dev.overpass-api.de/api_drolbr/
      OVERPASS_DIFF_URL: https://planet.openstreetmap.org/replication/minute/
      OVERPASS_UPDATE_SLEEP: 3600
      OVERPASS_FASTCGI_PROCESSES: 2
      OVERPASS_SPACE: 6000000000
    volumes:
      - /mnt/applications/overpass:/db
    networks:
      - traefik_default
      - default
    healthcheck:
      interval: 15m
    labels:
      traefik.enable: true
      traefik.http.routers.overpass.entrypoints: websecure
      traefik.http.routers.overpass.rule: Host(`${DOMAIN}`)
    restart: unless-stopped
networks:
  traefik_default:
    external: true
x-dockge:
  urls:
    - https://${DOMAIN}
