services:
  webserver:
    image: jdemaeyer/brightsky:v2.2.5
    command: serve --bind 0.0.0.0:5000
    environment:
      BRIGHTSKY_DATABASE_URL: postgres://brightsky:brightsky@postgres:5432
    networks:
      - default
      - traefik_default
    labels:
      traefik.enable: true
      traefik.http.routers.brightsky.entrypoints: websecure
      traefik.http.routers.brightsky.rule: Host(`${DOMAIN}`)
      traefik.http.services.brightsky.loadbalancer.server.port: 5000
    restart: unless-stopped
    depends_on:
      - postgres

  worker:
    image: jdemaeyer/brightsky:v2.2.5
    command: --migrate work
    environment:
      BRIGHTSKY_DATABASE_URL: postgres://brightsky:brightsky@postgres:5432
      BRIGHTSKY_REDIS_URL: redis://valkey:6379
      BRIGHTSKY_MIN_DATE: "2018-01-01"
      BRIGHTSKY_POLLING_CRONTAB_MINUTE: "*/30"
    restart: unless-stopped
    depends_on:
      - postgres
      - valkey

  postgres:
    image: postgres:16.8-alpine3.21
    shm_size: 512mb
    environment:
      POSTGRES_DB: brightsky
      POSTGRES_USER: brightsky
      POSTGRES_PASSWORD: brightsky
    volumes:
      - /mnt/applications/brightsky/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  valkey:
    image: valkey/valkey:8.0.1-alpine3.20
    volumes:
      - /mnt/applications/brightsky/valkey:/data
    restart: unless-stopped

networks:
  traefik_default:
    external: true

x-dockge:
  urls:
    - https://${DOMAIN}
