apiVersion: v2
type: application
name: traefik
version: 1.0.8
appVersion: "2.10.4"
kubeVersion: '>=1.16.0-0'
description: Traefik is a flexible reverse proxy and Ingress Provider.
home: https://traefik.io/
icon: https://truecharts.org/img/hotlink-ok/chart-icons/traefik.png
maintainers:
  - name: Jan Sauer
    url: https://jansauer.de/
    email: jan@jansauer.de
sources:
  - https://github.com/truecharts/charts/tree/master/charts/enterprise/traefik
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
  - https://traefik.io/
  - https://doc.traefik.io/traefik/
keywords:
  - jansauer
  - traefik
  - ingress
