apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "ix-storage-class-{{ .Release.Name }}"
provisioner: zfs.csi.openebs.io
parameters:
  fstype: zfs
  poolname: "applications/ix-applications/releases/{{ .Release.Name }}/volumes"
  shared: "yes"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
