services:
  app:
    image: actualbudget/actual-server:25.4.0-alpine
    volumes:
      - /mnt/applications/actual:/data
    networks:
      - traefik_default
    labels:
      traefik.enable: true
      traefik.http.routers.actual.entrypoints: websecure
      traefik.http.routers.actual.rule: Host(`${DOMAIN}`)
    restart: unless-stopped

networks:
  traefik_default:
    external: true

x-dockge:
  urls:
    - https://${DOMAIN}
