apiVersion: v2
type: application
name: grafana
version: "0.0.6"
appVersion: "11.1.0"
kubeVersion: ">=1.16.0-0"
description: Grafana is a analytics and monitoring platform.
home: https://grafana.com/oss/grafana/
icon: https://truecharts.org/img/hotlink-ok/chart-icons/grafana.webp
maintainers:
  - name: Jan Sauer
    url: https://jansauer.de/
    email: jan@jansauer.de
sources:
  - https://grafana.com/grafana/
  - https://hub.docker.com/r/grafana/grafana
keywords:
  - jansauer
  - monitoring
