http:
  routers:
    truenas:
      entryPoints:
        - websecure
      service: truenas
      rule: Host(`${TRUENAS_DOMAIN}`)

  services:
    truenas:
      loadBalancer:
        servers:
          - url: https://192.168.5.5:8443/
