services:
  server:
    image: ghcr.io/immich-app/immich-server:v3.0.3
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: valkey
    volumes:
      - /mnt/applications/immich/upload:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
      newt_default:
        aliases:
          - immich
    healthcheck:
      disable: true
    restart: unless-stopped
    labels:
      - pangolin.proxy-resources.immich.name=Immich
      - pangolin.proxy-resources.immich.full-domain=immich.${DOMAIN}
      - pangolin.proxy-resources.immich.protocol=http
      - pangolin.proxy-resources.immich.auth.sso-enabled=true
      - pangolin.proxy-resources.immich.targets[0].method=http
      - pangolin.proxy-resources.immich.targets[0].hostname=immich
      - pangolin.proxy-resources.immich.targets[0].port=2283
      - pangolin.proxy-resources.immich.targets[0].healthcheck.hostname=immich
      - pangolin.proxy-resources.immich.targets[0].healthcheck.port=2283
      - pangolin.proxy-resources.immich.targets[0].healthcheck.path=/api/server/ping
      - pangolin.proxy-resources.immich.rules[0].action=allow
      - pangolin.proxy-resources.immich.rules[0].match=path
      - pangolin.proxy-resources.immich.rules[0].value=/.well-known/immich
      - pangolin.proxy-resources.immich.rules[1].action=allow
      - pangolin.proxy-resources.immich.rules[1].match=path
      - pangolin.proxy-resources.immich.rules[1].value=/api/*
    depends_on:
      - postgres
      - valkey

  ml:
    image: ghcr.io/immich-app/immich-machine-learning:v3.0.3-openvino
    volumes:
      - /mnt/applications/immich/model-cache:/cache
    healthcheck:
      disable: true
    restart: unless-stopped

  postgres:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - /mnt/applications/immich/postgres:/var/lib/postgresql/data
    healthcheck:
      disable: true
    shm_size: 128mb
    restart: unless-stopped

  valkey:
    image: valkey/valkey:9.1.0-alpine
    volumes:
      - /mnt/applications/immich/valkey:/data
    restart: unless-stopped

networks:
  newt_default:
    external: true
