services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
    environment:
      PAPERLESS_REDIS: redis://valkey:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_URL: https://paperless.${DOMAIN}
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >-
        {"openid_connect":{"SCOPE":["openid","profile","email"],"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"pocketid","name":"Pocket ID","client_id":"${PAPERLESS_OIDC_CLIENT_ID}","secret":"${PAPERLESS_OIDC_CLIENT_SECRET}","settings":{"server_url":"${OIDC_ISSUER_URL}"}}]}}
      PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
      PAPERLESS_SOCIAL_AUTO_SIGNUP: "false"
      PAPERLESS_DISABLE_REGULAR_LOGIN: "true"
      PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
    volumes:
      - /mnt/applications/paperless-ngx/data:/usr/src/paperless/data
      - /mnt/applications/paperless-ngx/media:/usr/src/paperless/media
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
      newt_default:
        aliases:
          - paperless
    healthcheck:
      disable: true
    restart: unless-stopped
    labels:
      - pangolin.proxy-resources.paperless.name=Paperless
      - pangolin.proxy-resources.paperless.full-domain=paperless.${DOMAIN}
      - pangolin.proxy-resources.paperless.protocol=http
      - pangolin.proxy-resources.paperless.auth.sso-enabled=true
      - pangolin.proxy-resources.paperless.targets[0].method=http
      - pangolin.proxy-resources.paperless.targets[0].hostname=paperless
      - pangolin.proxy-resources.paperless.targets[0].port=8000
      - pangolin.proxy-resources.paperless.targets[0].healthcheck.hostname=paperless
      - pangolin.proxy-resources.paperless.targets[0].healthcheck.port=8000
      - pangolin.proxy-resources.paperless.targets[0].healthcheck.path=/
    depends_on:
      - postgres
      - valkey

  postgres:
    image: postgres:18.4-alpine3.23
    shm_size: 256mb
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - /mnt/applications/paperless-ngx/postgres:/var/lib/postgresql/18/docker
    restart: unless-stopped

  valkey:
    image: valkey/valkey:9.1.0-alpine
    volumes:
      - /mnt/applications/paperless-ngx/valkey:/data
    restart: unless-stopped

networks:
  newt_default:
    external: true
